%YAML 1.1
# Configuration file
# Plugins should have a plugin_run() function to execute and return results.
---
plugins:
    basic_metrics:
        type: analysis
        subtype: metrics
    radon_rules:
        type: analysis
        subtype: rules
    cccc_rules:
        type: analysis
        subtype: rules
    cpplint_plugin:
        type: analysis
        subtype: rules
