%YAML 1.1
# Configuration file
# Plugins should have a plugin_run() function to execute and return results.
---
export:
    format: csv
plugins_unused:
    basic_metrics:
        type: analysis
        subtype: metrics
plugins_all:
    radon_rules:
        type: analysis
        subtype: rules
    cccc_rules:
        type: analysis
        subtype: rules
    cpplint_plugin:
        type: analysis
        subtype: rules
    cppcheck_plugin:
        type: analysis
        subtype: rules
        needs:
            - cppcheck_rules.xml
plugins:
    cccc_rules:
        type: analysis
        subtype: rules
    ccd_plugin:
        type: analysis
        subtype: rules
    cpplint_plugin:
        type: analysis
        subtype: rules
    cppcheck_plugin:
        type: analysis
        subtype: rules
        needs:
            - cppcheck_rules.xml
