%YAML 1.1
# Configuration file
# Plugins should have a plugin_run() function to execute and return results.
---
plugins_unused:
    basic_metrics:
        type: analysis
        subtype: metrics
plugins:
    radon_rules:
        type: analysis
        subtype: rules
    cccc_rules:
        type: analysis
        subtype: rules
    cpplint_plugin:
        type: analysis
        subtype: rules
    cppcheck_plugin:
        type: analysis
        subtype: rules
plugins_test:
    cppcheck_plugin:
        type: analysis
        subtype: rules
